### ISSUE TITLE
Views CSS grid already in Backdrop core

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/views_css_grid#1]
There's probably still a good usecase for this module, but I'd just like to note that the CSS grid functionality has been added to the core "Grid" display for views (replacing what was a HTML table in Drupal 7). 

There may be people who used this module in Drupal 7 but only need the core Grid display for Backdrop.

**Comment by albanycomputers** [comment]
My intention is for this module to be usable by site builders who do not want to create custom themes and custom CSS. It also has the facility to use CSS Fit or Fill and over time it will have a few different styles as well as masonry displays.
